#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

./Allmesh

test=false
for arg in "$@"; do
    case "$arg" in
        --test)
            test=true
            ;;
    esac
done

if [ "$test" = true ]; then
    echo "Running test in single core and one iteration"
    sed -i 's/endTime;/writeNow;/g' system/controlDict
    runApplication foamRun
    sed -i 's/writeNow;/endTime;/g' system/controlDict
    
    if grep -q "End" log.foamRun; then
     echo "Test ran succesfully"
    else
     echo "Test failed"
    fi
else
    runApplication decomposePar -fileHandler collated
    runParallel foamRun -fileHandler collated
    runApplication reconstructPar -fileHandler collated
fi


#------------------------------------------------------------------------------
