#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

./Allmesh

#runApplication decomposePar -fileHandler collated
runParallel foamRun -fileHandler collated
runApplication -a reconstructPar -fileHandler collated


#------------------------------------------------------------------------------
