#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
runApplication createPatch -overwrite
runApplication setFields


test=false
for arg in "$@"; do
    case "$arg" in
        --test)
            test=true
            ;;
    esac
done

if [ "$test" = true ]; then
    echo "Running test in single core and one iteration"
    sed -i 's/endTime;/writeNow;/g' system/controlDict
    runApplication foamRun
    sed -i 's/writeNow;/endTime;/g' system/controlDict
    
    if grep -q "End" log.foamRun; then
     echo "Test ran succesfully"
    else
     echo "Test failed"
    fi
else
    runApplication decomposePar 
    runParallel foamRun 
fi


#------------------------------------------------------------------------------
