#!/bin/bash
##SBATCH --qos=high
#SBATCH --job-name=formicAcid04
##SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20  # use 52
#SBATCH --time=2-00:00:00
#SBATCH --account=gas2fuels
#SBATCH --output=log.out
#SBATCH --error=log.err
#SBATCH --dependency=singleton
#SBATCH --distribution=cyclic:cyclic

module purge
ml PrgEnv-cray
#source /projects/gas2fuels/ofoam_cray_mpich/OpenFOAM-dev/etc/bashrc
#ml openfoam/9-craympich
#. ./presteps.sh
module load openfoam/13-craympich-scotch
srun -n 20 -K1 --cpu_bind=cores foamRun -parallel 

# post-process
reconstructPar -newTimes

