#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm 0/alpha.gas
rm 0/alpha.liquid

cp ../geometry/STR.zip .

unzip STR.zip

runApplication ideasUnvToFoam STR.unv
runApplication changeDictionary

runApplication checkMesh -allGeometry -allTopology
runApplication setFields
#------------------------------------------------------------------------------
