#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm -rf 0/alpha.gas
rm -rf 0/alpha.liquid

unzip ../geometry/STR_rotating.zip STR_rotating.unv

runApplication ideasUnvToFoam STR_rotating.unv
runApplication changeDictionary

runApplication createBaffles
runApplication splitBaffles 

runApplication renumberMesh -noFields

runApplication createNonConformalCouples nonCouple2 nonCouple1 

runApplication checkMesh -allGeometry -allTopology
runApplication setFields
runApplication decomposePar -fileHandler collated
#------------------------------------------------------------------------------
