#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
surfaceFeatures
snappyHexMesh 

createPatch 

createBaffles #-flipMap
splitBaffles 

renumberMesh -noFields

createNonConformalCouples nonCouple1 nonCouple2

checkMesh

setFields

#------------------------------------------------------------------------------
