#!/bin/bash
##SBATCH --qos=high
#SBATCH --job-name=s350flow
##SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=100  # use 52
#SBATCH --time=2-00:00:00
##SBATCH --time=0-02:00:00
#SBATCH --account=gas2fuels
#SBATCH --output=log.out
#SBATCH --error=log.err
#SBATCH --dependency=singleton
#SBATCH --distribution=cyclic:cyclic
#SBATCH --mail-user=fmunicch@nlr.gov
#SBATCH --mail-type=BEGIN,END,FAIL


module purge
ml PrgEnv-cray
#source /projects/gas2fuels/ofoam_cray_mpich/OpenFOAM-dev/etc/bashrc
#ml openfoam/9-craympich
#. ./presteps.sh
module load openfoam/13-craympich-scotch
srun -n 100 -K1 --cpu-bind=v,rank_ldom  foamRun -parallel -fileHandler collated

# post-process
reconstructPar -newTimes

