#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm 0/alpha.gas
rm 0/alpha.liquid

runApplication blockMesh
runApplication decomposePar -copyZero -fileHandler collated
runParallel snappyHexMesh -fileHandler collated

runParallel setFields -fileHandler collated
runApplication reconstructPar -withZero -fields '(alpha.gas alpha.liquid)' -fileHandler collated


runParallel foamRun -fileHandler collated
runApplication -a reconstructPar -fileHandler collated


#------------------------------------------------------------------------------
