#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
rm log.foamRun
runParallel foamRun -fileHandler collated
runApplication -a reconstructPar -newTimes

#------------------------------------------------------------------------------
