#!/bin/bash
#SBATCH --job-name=val2
##SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=01:59:00
#SBATCH --account=gas2fuels

source /projects/gas2fuels/ofoam_cray_mpich/OpenFOAM-dev/etc/bashrc
reconstructPar -newTimes -fields "(Z.liquid U.liquid alpha.gas)"
module load conda
conda activate /projects/gas2fuels/conda_env/bird_mixer
python get_mixing_time.py 
