name: bird-CI

on:
   push:
     branches: [main]
     paths-ignore:
      - '*.md'
      - '*.rst'
      - 'README*'
      - 'LICENSE'
      - 'docs/**'

   pull_request:
     branches: [main]
     paths-ignore:
      - '*.md'
      - '*.rst'
      - 'README*'
      - 'LICENSE'
      - 'docs/**'

permissions:
  contents: read

jobs:
  Lint:
    name: Lint (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14']
        os: ['ubuntu-latest']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'

      - name: Cache Nox
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-lint-nox-${{ hashFiles('noxfile.py') }}

      - name: Install nox
        run: pip install nox

      - name: Formatting and sorting import
        run: nox -s linter

      - name: Spellcheck
        run: nox -s spell

  Unit-Test-BiRD:
    name: Unit-Test-BiRD (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.14']
        os: ['ubuntu-latest', 'macos-latest']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          cache-downloads: true
          cache-env: true

      - name: Install dependencies
        run: |
          micromamba install --yes -n test-env -c conda-forge paraview
          pip install --upgrade pip
          pip install --upgrade nox
          pip install .[tests] 

      - name: Test
        run: nox -s tests -- no-reports

  Unit-Test-pixi-BiRD:
    name: Unit-Test-pixi-BiRD (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Formatting and sorting import
        run: |
          pixi run test

  Unit-Test-pypi-Bird:
    name: Unit-Test-pypi-BiRD (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14']
        os: ['ubuntu-latest']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          cache-downloads: true
          cache-env: true

      - name: Install dependencies
        run: |
          micromamba install --yes -n test-env -c conda-forge paraview
          pip install --upgrade pip
          pip install --upgrade nox
          pip install nlr-bird[tests]

      - name: Test
        run: nox -s tests -- no-reports

  Regression-Test-OF:
    name: Regression-Test-OF (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14']
        os: ['ubuntu-22.04']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: 9

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          cache-downloads: true
          cache-env: true

      - name: Install dependencies
        run: |
          micromamba install --yes -n test-env -c conda-forge paraview
          pip install --upgrade pip
          pip install .

      - name: Compile solver
        run: |
          cd OFsolvers/OF9/birdmultiphaseEulerFoam
          export WM_COMPILE_OPTION=Debug
          ./Allwmake
          cd ../../../
      - name: Run deckwer17 PBE
        run: |
          cd experimental_cases/OF9/deckwer17
          bash run.sh 
          cd ../../../
      - name: Run deckwer17 constantD
        run: |
          cd experimental_cases/OF9/deckwer17
          cp constant/phaseProperties_constantd constant/phaseProperties
          bash run.sh 
          cd ../../../
      - name: Run deckwer19 PBE
        run: |
          cd experimental_cases/OF9/deckwer19
          bash run.sh 
          cd ../../../
      - name: Run side sparger tutorial
        run: |
          cd tutorial_cases/OF9/side_sparger
          bash run.sh 
          cd ../../../
      - name: Run bubble column tutorial
        run: |
          cd tutorial_cases/OF9/bubble_column_20L
          bash run.sh 
          cd ../../../
      - name: Run stirred-tank tutorial
        run: |
          cd tutorial_cases/OF9/stirred_tank
          bash run.sh 
          cd ../../../
      - name: Run reactive loop reactor tutorial
        run: |
          cd tutorial_cases/OF9/loop_reactor_reacting
          bash run.sh 
          cd ../../../
      - name: Run mixing loop reactor tutorial
        run: |
          cd tutorial_cases/OF9/loop_reactor_mixing
          bash run.sh 
          cd ../../../
      - name: Run airlift reactor tutorial
        run: |
          cd tutorial_cases/OF9/airlift_40m
          bash run.sh
          cd ../../../
      - name: Run flat panel reactor tutorial
        run: |
          cd tutorial_cases/OF9/FlatPanel_250L_ASU
          bash run.sh
          cd ../../../

  Regression-Test-OF-pixi:
    name: Regression-Test-OF-pixi (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04']
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: 9
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Compile solver
        run: |
          cd OFsolvers/OF9/birdmultiphaseEulerFoam
          export WM_COMPILE_OPTION=Debug
          ./Allwmake
          cd ../../../
      - name: Run bubble column tutorial
        run: |
          cd tutorial_cases/OF9/bubble_column_20L
          bash run_pixi.sh 
          cd ../../../

